FROM python:3.10-slim
WORKDIR /app
COPY services/monitoring_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . /app
EXPOSE 8002
CMD ["uvicorn","services.monitoring_service.main:app","--host","0.0.0.0","--port","8002"]
